### ISSUE TITLE
[FEATURE]: Adding to board - does it filter or remove duplications? 

### ISSUE THREAD

**Issue by angiegustiloong** [UNDP-Accelerator-Labs/sdg-innovation-commons#101]
### What areas do you propose needs enhancement or improvement?

I can't tell when I add things if there is duplication, would be great if automatically duplications are not seen in the board, or that there is a pop up to say this has already been added to the board?

**Comment by myjyby** [comment]
hi @angiegustiloong. Indeed content is not duplicated on a board, however many times you might add the same entry to a given board.
