### ISSUE TITLE
[Bug]: Link to pinboards doesn't work

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#18]
### Issue description

Either from the top menu item "next practices" or the "pinboard" section on the home page, we can not access any pinboards.

### Where did this happen?

Nov 11.

### What do you expect?

Go to all pinboards when clicking on "next practices" or go to the specific boards when clicking on board examples.

### What browsers are you seeing the problem on?

Firefox

**Comment by myjyby** [comment]
Duly noted, thanks. Indeed we need to design these and link them.
