### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by egustale** [UNDP-Accelerator-Labs/sdg-innovation-commons#20]
### Issue description

In the thumbnail results some action plans descriptions are too long and they alter the entire search results. 
![Screenshot 2024-11-12 at 8 51 14 AM](https://github.com/user-attachments/assets/ed8f633b-bb95-4921-a2b3-6d9b9c2960d4)

### Where did this happen?

When searching for "Governance" the action plan "Closing Form: Citizen Participation, Trust and Social Capital" is too long, having to scroll down a lot to see the next search results.

### What do you expect?

Thumbnail text descriptions to be limited so that its easy to scroll through search results.

### What browsers are you seeing the problem on?

Chrome

**Comment by myjyby** [comment]
This should be solved now. Snippets are sliced after 200 characters.
