### ISSUE TITLE
[Bug]: CTA "join the platform" doesn't make much sense

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#47]
### Issue description

It's not exactly a bug, but it doesn't help the navigation as it sends people to the contact form, when the copy says: Sign up and join.

### Where did this happen?

![image](https://github.com/user-attachments/assets/094c2994-471d-49cc-9f0b-6b8ed51df2f1)

### What do you expect?

Suggest to remove entirely the CTA above: "Sign up for your plaftorm" and edit the copy in the CTA button to "Sign up" and link it to the SSO form.

### What browsers are you seeing the problem on?

Firefox

**Comment by ErikaAntoine** [comment]
Added it to the copy document that Dappo is working on, as I am not sure where to address this issue: here or copy related?

**Comment by myjyby** [comment]
I removed the CTA and changed the button link to point to the login page in #54 .
