### ISSUE TITLE
[Bug]: Sometimes the menu disappears

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#58]
### Issue description

I just logged in using SSO, came back to the homepage scroll down and up again and the header menu disappeared.

### Where did this happen?

Home page
![image](https://github.com/user-attachments/assets/4468f66e-8800-4216-bcaa-5ec5493a49bd)

### What do you expect?

Header menu to stay visible at all times.

### What browsers are you seeing the problem on?

Firefox

**Comment by myjyby** [comment]
This is the expected behavior, as per Ahoy's design recommendations.
