### ISSUE TITLE
[FEATURE]: Add magnifying loop in the main header menu

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#63]
### What areas do you propose needs enhancement or improvement?

Could we add an icon of the magnifying loop at the top of the header menu? Since the SDG Commons is meant to be a place to search for content, it is critical we get this access as quick and friction-less as possible. This would add a lot of coherence with our main website. 

### Where is the current state/behavior?

To search for content one needs to be on the home page and use the search field in the hero image. It's not readily available in the header menu.

### How would it improve the project?

Add a simple magnifying loop icon like on our main website
![image](https://github.com/user-attachments/assets/b2cad444-9240-45fa-a938-5dbb9f6aeb42)

### Add why this is beneficial.

Direct access to search.

**Comment by this-pama** [comment]
This will be available with the next release in PR #67.

**Comment by ErikaAntoine** [comment]
Great, many thanks! When can we expect this next release to happen roughly?
