### ISSUE TITLE
[FEATURE]: Add anchor(s) on a url so we can link directly to the contact form

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#64]
### What areas do you propose needs enhancement or improvement?

Allow for more specific url for the homepage with an anchor to go straight to the contact form.

### Where is the current state/behavior?

Only one url, the main home page which points to the top of the page.

### How would it improve the project?

Allow to hyperlink to where we provide an access to give feedback and share ideas.

**Comment by this-pama** [comment]
This will be available in next release #67
