### ISSUE TITLE
[Bug]: On a main search filters do not work

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#66]
### Issue description

I am using the main search (from the home page) for "health AI" and once the results appear, I would like to use the filter to narrow the results down to country = Egypt. But I do not see the country drop down and I cannot type and select Egypt neither.

### Where did this happen?

Home
![image](https://github.com/user-attachments/assets/d5940455-979a-466c-9397-f8a0919c842e)

### What do you expect?

filters component to open, show me the country drop down for me to select, and countries/country selected to appear as filters.

### What browsers are you seeing the problem on?

Chrome

**Comment by this-pama** [comment]
Thanks for reporting this. This will be fixed with the next release in PR #67
