### ISSUE TITLE
[Bug]: Add the disclaimer back in each learning plans + in the about us page

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#78]
### Issue description

Can you please add the disclaimer we had on the old platform to each learning plan and in the about us page?

### Where did this happen?

About us + each learning plan page.

### What do you expect?

**Add the following line for the learning plans:**
Disclaimer:
Please be aware that the content herein has not been peer reviewed. It consists of personal reflections, insights, and learnings of the contributor(s). It may not to be exhaustive, nor does it aim to be authoritative knowledge. 

**Add the following line for the about us:**
Disclaimer:
Please be aware that the content published here has not been peer reviewed. It consists of personal reflections, insights, and learnings of the contributor(s). It may not to be exhaustive, nor does it aim to be authoritative knowledge.

**Comment by this-pama** [comment]
Noted with thanks. This will be available with the coming release in #77
