### ISSUE TITLE
[Bug]: "Options" button doesn't work for me

### ISSUE THREAD

**Issue by ErikaAntoine** [UNDP-Accelerator-Labs/sdg-innovation-commons#86]
### Issue description

When I try to click on "options" nothing happens. Not sure what was supposed to be here. Perhaps we should also think about labeling this button differently? What is it supposed to offer?

### Where did this happen?

![image](https://github.com/user-attachments/assets/873f9edf-3eea-460a-a744-fc325ee6e795)
https://sdg-innovation-commons.org/test/all

### What do you expect?

Not entirely sure, as I don't remember well what this button's function is. Perhaps "Sort content" as a way to indicate that more filters are included? Unclear why we have "Filters" and "Options" as two separate buttons. Ideally one single button with all filters and pre-set filters inside would be easier for the user.

### What browsers are you seeing the problem on?

Firefox

**Comment by this-pama** [comment]
Fixed in #89. The option button will no longer be available if the current user does not have the rights to perform any of the outlined actions.
